"""
Mako script used for generating migration files.

This is the default template that Alembic uses when creating new migration files.
"""

"""Initial database schema with all models

Revision ID: ebc9b8f1cdd1
Revises:
Create Date: 2026-02-08 14:10:29.439469+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebc9b8f1cdd1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="User's primary email address",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="User's display name"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether user account is active",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="User who owns this API key"),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="User-chosen descriptive name for the key",
        ),
        sa.Column(
            "key_hash",
            sa.Text(),
            nullable=False,
            comment="Hashed secret portion of the API key",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when key was last used (UTC)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether the key is active (for revocation)",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column(
            "owner_id",
            sa.UUID(),
            nullable=True,
            comment="User who owns this job (NULL for orphaned legacy jobs)",
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="User-provided job title",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="User-provided job description",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            server_default="pending",
            nullable=False,
            comment="Current job status (pending/running/completed/failed/cancelled)",
        ),
        sa.Column(
            "max_iterations",
            sa.Integer(),
            server_default="5",
            nullable=False,
            comment="Maximum number of analysis iterations allowed",
        ),
        sa.Column(
            "current_iteration",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Current iteration number (0-based)",
        ),
        sa.Column(
            "pdb_code",
            sa.String(length=10),
            nullable=True,
            comment="PDB code if analyzing existing structure",
        ),
        sa.Column(
            "space_group",
            sa.String(length=50),
            nullable=True,
            comment="Crystal space group",
        ),
        sa.Column(
            "resume_iteration",
            sa.Integer(),
            nullable=True,
            comment="Iteration to resume from (NULL for new jobs)",
        ),
        sa.Column(
            "llm_provider",
            sa.String(length=50),
            server_default="vertex",
            nullable=False,
            comment="LLM provider being used (vertex/bedrock/cborg)",
        ),
        sa.Column(
            "llm_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="LLM configuration (model, temperature, etc.)",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Error message if job failed",
        ),
        sa.Column("result_summary", sa.Text(), nullable=True, comment="Final analysis summary"),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_owner_id"), "jobs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "oauth_accounts",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="User who owns this OAuth account",
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="OAuth provider name (github, orcid)",
        ),
        sa.Column(
            "provider_user_id",
            sa.String(length=255),
            nullable=False,
            comment="User's unique ID on the OAuth provider",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Email address from OAuth provider",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Display name from OAuth provider",
        ),
        sa.Column(
            "access_token",
            sa.Text(),
            nullable=True,
            comment="OAuth access token (encrypted in production)",
        ),
        sa.Column(
            "refresh_token",
            sa.Text(),
            nullable=True,
            comment="OAuth refresh token (encrypted in production)",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_oauth_provider_user"),
    )
    op.create_index(
        op.f("ix_oauth_accounts_provider"), "oauth_accounts", ["provider"], unique=False
    )
    op.create_index(op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="User who owns this session"),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when session expires (UTC)",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP address where session was created",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="Browser user agent string",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "analysis_log",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this log entry belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number when entry was created",
        ),
        sa.Column(
            "step_number",
            sa.Integer(),
            nullable=False,
            comment="Sequential step number within iteration",
        ),
        sa.Column(
            "action_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of action (reasoning/code_execution/literature_search/etc)",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Human-readable description of the action",
        ),
        sa.Column(
            "input_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Input data for this step",
        ),
        sa.Column(
            "output_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Output/result data from this step",
        ),
        sa.Column(
            "duration_seconds",
            sa.Float(),
            nullable=True,
            comment="Time taken for this step",
        ),
        sa.Column(
            "success",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether the step completed successfully",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Error message if step failed",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analysis_log_job_id"), "analysis_log", ["job_id"], unique=False)
    op.create_table(
        "cost_records",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this cost belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=True,
            comment="Iteration number when cost was incurred (NULL for chat)",
        ),
        sa.Column(
            "operation_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of operation (analysis/code_gen/chat/etc)",
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="LLM provider (vertex/bedrock/cborg)",
        ),
        sa.Column("model", sa.String(length=100), nullable=False, comment="Model name/ID used"),
        sa.Column(
            "input_tokens",
            sa.Integer(),
            nullable=False,
            comment="Number of input tokens",
        ),
        sa.Column(
            "output_tokens",
            sa.Integer(),
            nullable=False,
            comment="Number of output tokens",
        ),
        sa.Column("cost_usd", sa.Float(), nullable=False, comment="Cost in USD"),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_records_job_id"), "cost_records", ["job_id"], unique=False)
    op.create_table(
        "feedback_history",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this feedback belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number when feedback was provided",
        ),
        sa.Column(
            "feedback_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of feedback (correction/suggestion/question/approval)",
        ),
        sa.Column("feedback_text", sa.Text(), nullable=False, comment="User's feedback text"),
        sa.Column(
            "response_text",
            sa.Text(),
            nullable=True,
            comment="LLM's response to the feedback",
        ),
        sa.Column(
            "applied",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether feedback has been incorporated",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_history_job_id"), "feedback_history", ["job_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this finding belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number when finding was generated",
        ),
        sa.Column("text", sa.Text(), nullable=False, comment="Finding description"),
        sa.Column(
            "finding_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of finding (observation/measurement/analysis/error)",
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="Source of finding (code_execution/literature/reasoning)",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structured data associated with finding",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_job_id"), "findings", ["job_id"], unique=False)
    op.create_table(
        "hypotheses",
        sa.Column(
            "job_id",
            sa.UUID(),
            nullable=False,
            comment="Job this hypothesis belongs to",
        ),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number when hypothesis was generated",
        ),
        sa.Column("text", sa.Text(), nullable=False, comment="Hypothesis statement"),
        sa.Column(
            "status",
            sa.String(length=50),
            server_default="active",
            nullable=False,
            comment="Current status (active/tested/disproved/merged/spawned)",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
            comment="Confidence score (0.0-1.0)",
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=True,
            comment="Priority for testing (higher = more important)",
        ),
        sa.Column(
            "rationale",
            sa.Text(),
            nullable=True,
            comment="Reasoning behind the hypothesis",
        ),
        sa.Column(
            "test_strategy",
            sa.Text(),
            nullable=True,
            comment="Proposed method for testing",
        ),
        sa.Column(
            "supporting_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Evidence supporting this hypothesis",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hypotheses_job_id"), "hypotheses", ["job_id"], unique=False)
    op.create_table(
        "iteration_summaries",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this summary belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number being summarized",
        ),
        sa.Column(
            "summary_text",
            sa.Text(),
            nullable=False,
            comment="Natural language summary of iteration",
        ),
        sa.Column(
            "key_findings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of important findings from this iteration",
        ),
        sa.Column(
            "hypotheses_generated",
            sa.Integer(),
            nullable=True,
            comment="Number of new hypotheses generated",
        ),
        sa.Column(
            "hypotheses_tested",
            sa.Integer(),
            nullable=True,
            comment="Number of hypotheses tested",
        ),
        sa.Column(
            "code_executed",
            sa.Integer(),
            nullable=True,
            comment="Number of code blocks executed",
        ),
        sa.Column(
            "new_insights",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of new insights gained",
        ),
        sa.Column(
            "next_steps",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Planned next steps",
        ),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structured metrics (e.g., R-factors, completeness)",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iteration"),
    )
    op.create_index(
        op.f("ix_iteration_summaries_job_id"),
        "iteration_summaries",
        ["job_id"],
        unique=False,
    )
    op.create_table(
        "job_chat_messages",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this message belongs to"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Message role (user/assistant)",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="Message text content"),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_chat_messages_job_id"),
        "job_chat_messages",
        ["job_id"],
        unique=False,
    )
    op.create_table(
        "job_data_files",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this file belongs to"),
        sa.Column(
            "filename",
            sa.String(length=255),
            nullable=False,
            comment="Original filename as uploaded by user",
        ),
        sa.Column(
            "file_path",
            sa.String(length=500),
            nullable=False,
            comment="Relative path to file on filesystem",
        ),
        sa.Column(
            "file_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of file (mtz/cif/pdb/other)",
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=False, comment="File size in bytes"),
        sa.Column(
            "mime_type",
            sa.String(length=100),
            nullable=True,
            comment="MIME type of the file",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_data_files_job_id"), "job_data_files", ["job_id"], unique=False)
    op.create_table(
        "job_shares",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job being shared"),
        sa.Column(
            "shared_with_user_id",
            sa.UUID(),
            nullable=False,
            comment="User being granted access",
        ),
        sa.Column(
            "permission_level",
            sa.String(length=10),
            nullable=False,
            comment="Permission level (view/edit)",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.CheckConstraint("permission_level IN ('view', 'edit')", name="ck_job_share_permission"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shared_with_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "shared_with_user_id", name="uq_job_share_user"),
    )
    op.create_index(op.f("ix_job_shares_job_id"), "job_shares", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_job_shares_shared_with_user_id"),
        "job_shares",
        ["shared_with_user_id"],
        unique=False,
    )
    op.create_table(
        "literature",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this reference belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number when reference was retrieved",
        ),
        sa.Column(
            "title",
            sa.String(length=500),
            nullable=False,
            comment="Title of the paper/document",
        ),
        sa.Column("authors", sa.Text(), nullable=True, comment="Author list"),
        sa.Column(
            "journal",
            sa.String(length=255),
            nullable=True,
            comment="Journal or publication venue",
        ),
        sa.Column("year", sa.Integer(), nullable=True, comment="Publication year"),
        sa.Column(
            "doi",
            sa.String(length=255),
            nullable=True,
            comment="Digital Object Identifier",
        ),
        sa.Column("url", sa.Text(), nullable=True, comment="URL to the resource"),
        sa.Column("abstract", sa.Text(), nullable=True, comment="Abstract or summary"),
        sa.Column(
            "relevance_score",
            sa.Float(),
            nullable=True,
            comment="Relevance to current analysis (0.0-1.0)",
        ),
        sa.Column(
            "citation_key",
            sa.String(length=100),
            nullable=True,
            comment="BibTeX citation key",
        ),
        sa.Column(
            "extra_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional structured metadata",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_literature_doi"), "literature", ["doi"], unique=False)
    op.create_index(op.f("ix_literature_job_id"), "literature", ["job_id"], unique=False)
    op.create_table(
        "plots",
        sa.Column("job_id", sa.UUID(), nullable=False, comment="Job this plot belongs to"),
        sa.Column(
            "iteration",
            sa.Integer(),
            nullable=False,
            comment="Iteration number when plot was generated",
        ),
        sa.Column("title", sa.String(length=255), nullable=False, comment="Plot title"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of what the plot shows",
        ),
        sa.Column(
            "file_path",
            sa.String(length=500),
            nullable=False,
            comment="Relative path to plot image file",
        ),
        sa.Column(
            "plot_type",
            sa.String(length=50),
            nullable=True,
            comment="Type of plot (histogram/scatter/heatmap/etc)",
        ),
        sa.Column(
            "code_used",
            sa.Text(),
            nullable=True,
            comment="Python code that generated the plot",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plots_job_id"), "plots", ["job_id"], unique=False)
    op.create_table(
        "finding_hypotheses",
        sa.Column(
            "finding_id",
            sa.UUID(),
            nullable=False,
            comment="Finding in this relationship",
        ),
        sa.Column(
            "hypothesis_id",
            sa.UUID(),
            nullable=False,
            comment="Hypothesis in this relationship",
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hypothesis_id"], ["hypotheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id", "hypothesis_id"),
        comment="Many-to-many relationship between findings and hypotheses",
    )
    op.create_table(
        "finding_literature",
        sa.Column(
            "finding_id",
            sa.UUID(),
            nullable=False,
            comment="Finding in this relationship",
        ),
        sa.Column(
            "literature_id",
            sa.UUID(),
            nullable=False,
            comment="Literature reference in this relationship",
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["literature_id"], ["literature.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id", "literature_id"),
        comment="Many-to-many relationship between findings and literature",
    )
    op.create_table(
        "hypothesis_spawns",
        sa.Column(
            "parent_id",
            sa.UUID(),
            nullable=False,
            comment="Parent hypothesis that spawned the child",
        ),
        sa.Column(
            "child_id",
            sa.UUID(),
            nullable=False,
            comment="Child hypothesis that was spawned",
        ),
        sa.Column(
            "spawn_reason",
            sa.Text(),
            nullable=True,
            comment="Explanation for why child was spawned",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["child_id"], ["hypotheses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["hypotheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hypothesis_spawns_child_id"),
        "hypothesis_spawns",
        ["child_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_spawns_parent_id"),
        "hypothesis_spawns",
        ["parent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hypothesis_spawns_parent_id"), table_name="hypothesis_spawns")
    op.drop_index(op.f("ix_hypothesis_spawns_child_id"), table_name="hypothesis_spawns")
    op.drop_table("hypothesis_spawns")
    op.drop_table("finding_literature")
    op.drop_table("finding_hypotheses")
    op.drop_index(op.f("ix_plots_job_id"), table_name="plots")
    op.drop_table("plots")
    op.drop_index(op.f("ix_literature_job_id"), table_name="literature")
    op.drop_index(op.f("ix_literature_doi"), table_name="literature")
    op.drop_table("literature")
    op.drop_index(op.f("ix_job_shares_shared_with_user_id"), table_name="job_shares")
    op.drop_index(op.f("ix_job_shares_job_id"), table_name="job_shares")
    op.drop_table("job_shares")
    op.drop_index(op.f("ix_job_data_files_job_id"), table_name="job_data_files")
    op.drop_table("job_data_files")
    op.drop_index(op.f("ix_job_chat_messages_job_id"), table_name="job_chat_messages")
    op.drop_table("job_chat_messages")
    op.drop_index(op.f("ix_iteration_summaries_job_id"), table_name="iteration_summaries")
    op.drop_table("iteration_summaries")
    op.drop_index(op.f("ix_hypotheses_job_id"), table_name="hypotheses")
    op.drop_table("hypotheses")
    op.drop_index(op.f("ix_findings_job_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_feedback_history_job_id"), table_name="feedback_history")
    op.drop_table("feedback_history")
    op.drop_index(op.f("ix_cost_records_job_id"), table_name="cost_records")
    op.drop_table("cost_records")
    op.drop_index(op.f("ix_analysis_log_job_id"), table_name="analysis_log")
    op.drop_table("analysis_log")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_index(op.f("ix_oauth_accounts_provider"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_owner_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
