"""Add skills tables

Revision ID: c5f2d4e3a1b8
Revises: b4e8d3c2f1a9
Create Date: 2026-02-11 14:30:00.000000+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5f2d4e3a1b8"
down_revision: Union[str, None] = "b4e8d3c2f1a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create skills, skill_sources, and job_skills tables."""

    # =========================================================================
    # SKILL_SOURCES - External repositories to sync skills from
    # =========================================================================
    op.create_table(
        "skill_sources",
        sa.Column(
            "source_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of source (github/local)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable name for the source",
        ),
        sa.Column(
            "url",
            sa.Text(),
            nullable=True,
            comment="URL for remote sources (e.g., GitHub repo URL)",
        ),
        sa.Column(
            "path",
            sa.Text(),
            nullable=True,
            comment="Local filesystem path for local sources",
        ),
        sa.Column(
            "branch",
            sa.String(length=255),
            server_default="main",
            nullable=False,
            comment="Git branch to sync from (for GitHub sources)",
        ),
        sa.Column(
            "skills_path",
            sa.String(length=255),
            server_default="",
            nullable=False,
            comment="Subdirectory within repo containing skills",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last successful sync",
        ),
        sa.Column(
            "last_commit_sha",
            sa.String(length=64),
            nullable=True,
            comment="Last synced Git commit SHA",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether this source is enabled for syncing",
        ),
        sa.Column(
            "sync_error",
            sa.Text(),
            nullable=True,
            comment="Error message from last failed sync attempt",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_sources_source_type"),
        "skill_sources",
        ["source_type"],
        unique=False,
    )

    # =========================================================================
    # SKILLS - Skill definitions with full-text search
    # =========================================================================
    op.create_table(
        "skills",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable skill name",
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-friendly identifier (unique within category)",
        ),
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=False,
            comment="Skill category (e.g., metabolomics, genomics, data-science)",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Brief description of what the skill does",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="Full markdown content of the skill",
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
            comment="Array of tags for filtering and search",
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            nullable=True,
            comment="Full-text search vector (auto-generated)",
        ),
        sa.Column(
            "source_id",
            sa.UUID(),
            nullable=True,
            comment="Skill source this skill was synced from (NULL for built-in)",
        ),
        sa.Column(
            "source_path",
            sa.Text(),
            nullable=True,
            comment="Path within source where skill was found",
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA256 hash of content for change detection",
        ),
        sa.Column(
            "commit_sha",
            sa.String(length=64),
            nullable=True,
            comment="Git commit SHA when skill was synced",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether this skill is available for use",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Version number for tracking updates",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["skill_sources.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category", "slug", name="uq_skill_category_slug"),
    )
    op.create_index(op.f("ix_skills_category"), "skills", ["category"], unique=False)
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=False)
    op.create_index(op.f("ix_skills_source_id"), "skills", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_skills_is_enabled"), "skills", ["is_enabled"], unique=False
    )

    # GIN index for full-text search on search_vector
    op.create_index(
        "ix_skills_search_vector",
        "skills",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )

    # GIN index for JSONB tags array
    op.create_index(
        "ix_skills_tags",
        "skills",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )

    # Create trigger function to auto-update search_vector
    op.execute(
        """
        CREATE OR REPLACE FUNCTION skills_search_vector_update() RETURNS TRIGGER AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', COALESCE(NEW.name, '')), 'A') ||
                setweight(to_tsvector('english', COALESCE(NEW.category, '')), 'B') ||
                setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'B') ||
                setweight(to_tsvector('english', COALESCE(NEW.content, '')), 'C');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """
    )

    # Create trigger to call the function
    op.execute(
        """
        CREATE TRIGGER skills_search_vector_trigger
            BEFORE INSERT OR UPDATE ON skills
            FOR EACH ROW
            EXECUTE FUNCTION skills_search_vector_update()
    """
    )

    # =========================================================================
    # JOB_SKILLS - Junction table linking skills to jobs
    # =========================================================================
    op.create_table(
        "job_skills",
        sa.Column(
            "job_id",
            sa.UUID(),
            nullable=False,
            comment="Job that this skill is attached to",
        ),
        sa.Column(
            "skill_id",
            sa.UUID(),
            nullable=False,
            comment="Skill attached to the job",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether this skill is enabled for the job",
        ),
        sa.Column(
            "relevance_score",
            sa.Float(),
            nullable=True,
            comment="Auto-match relevance score (0.0-1.0), NULL for manual selection",
        ),
        sa.Column(
            "match_reason",
            sa.Text(),
            nullable=True,
            comment="Explanation of why this skill was matched",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", "skill_id"),
    )
    op.create_index(
        op.f("ix_job_skills_job_id"), "job_skills", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_skills_skill_id"), "job_skills", ["skill_id"], unique=False
    )

    # =========================================================================
    # ROW-LEVEL SECURITY POLICIES
    # =========================================================================

    # skill_sources - Admin only (bypass_rls required)
    op.execute("ALTER TABLE skill_sources ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE skill_sources FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY skill_sources_bypass ON skill_sources FOR ALL
            USING (current_setting('app.bypass_rls', TRUE) = 'true')
    """
    )

    # skills - Public read, admin write
    op.execute("ALTER TABLE skills ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE skills FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY skills_select_all ON skills FOR SELECT
            USING (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND is_enabled = true
            )
    """
    )
    op.execute(
        """
        CREATE POLICY skills_bypass ON skills FOR ALL
            USING (current_setting('app.bypass_rls', TRUE) = 'true')
    """
    )

    # job_skills - Inherit access from jobs table
    op.execute("ALTER TABLE job_skills ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_skills FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY job_skills_bypass ON job_skills FOR ALL
            USING (current_setting('app.bypass_rls', TRUE) = 'true')
    """
    )
    # Job owner has full access
    op.execute(
        """
        CREATE POLICY job_skills_all_owner
            ON job_skills
            FOR ALL
            USING (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND EXISTS (
                    SELECT 1 FROM jobs
                    WHERE jobs.id = job_skills.job_id
                    AND jobs.owner_id::text = current_setting('app.current_user_id', TRUE)
                )
            )
    """
    )
    # Users with any job share can read
    op.execute(
        """
        CREATE POLICY job_skills_select_shared
            ON job_skills
            FOR SELECT
            USING (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND EXISTS (
                    SELECT 1 FROM jobs
                    JOIN job_shares ON job_shares.job_id = jobs.id
                    WHERE jobs.id = job_skills.job_id
                    AND job_shares.shared_with_user_id::text = current_setting('app.current_user_id', TRUE)
                )
            )
    """
    )
    # Users with 'edit' share can modify
    op.execute(
        """
        CREATE POLICY job_skills_modify_shared_edit
            ON job_skills
            FOR INSERT
            WITH CHECK (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND EXISTS (
                    SELECT 1 FROM jobs
                    JOIN job_shares ON job_shares.job_id = jobs.id
                    WHERE jobs.id = job_skills.job_id
                    AND job_shares.shared_with_user_id::text = current_setting('app.current_user_id', TRUE)
                    AND job_shares.permission_level = 'edit'
                )
            )
    """
    )
    op.execute(
        """
        CREATE POLICY job_skills_update_shared_edit
            ON job_skills
            FOR UPDATE
            USING (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND EXISTS (
                    SELECT 1 FROM jobs
                    JOIN job_shares ON job_shares.job_id = jobs.id
                    WHERE jobs.id = job_skills.job_id
                    AND job_shares.shared_with_user_id::text = current_setting('app.current_user_id', TRUE)
                    AND job_shares.permission_level = 'edit'
                )
            )
    """
    )
    op.execute(
        """
        CREATE POLICY job_skills_delete_shared_edit
            ON job_skills
            FOR DELETE
            USING (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND EXISTS (
                    SELECT 1 FROM jobs
                    JOIN job_shares ON job_shares.job_id = jobs.id
                    WHERE jobs.id = job_skills.job_id
                    AND job_shares.shared_with_user_id::text = current_setting('app.current_user_id', TRUE)
                    AND job_shares.permission_level = 'edit'
                )
            )
    """
    )


def downgrade() -> None:
    """Drop skills tables and related objects."""

    # Drop RLS policies
    for policy in [
        "job_skills_bypass",
        "job_skills_all_owner",
        "job_skills_select_shared",
        "job_skills_modify_shared_edit",
        "job_skills_update_shared_edit",
        "job_skills_delete_shared_edit",
    ]:
        op.execute(f"DROP POLICY IF EXISTS {policy} ON job_skills")
    op.execute("ALTER TABLE job_skills NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_skills DISABLE ROW LEVEL SECURITY")

    for policy in ["skills_select_all", "skills_bypass"]:
        op.execute(f"DROP POLICY IF EXISTS {policy} ON skills")
    op.execute("ALTER TABLE skills NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE skills DISABLE ROW LEVEL SECURITY")

    op.execute("DROP POLICY IF EXISTS skill_sources_bypass ON skill_sources")
    op.execute("ALTER TABLE skill_sources NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE skill_sources DISABLE ROW LEVEL SECURITY")

    # Drop trigger and function
    op.execute("DROP TRIGGER IF EXISTS skills_search_vector_trigger ON skills")
    op.execute("DROP FUNCTION IF EXISTS skills_search_vector_update()")

    # Drop tables
    op.drop_index(op.f("ix_job_skills_skill_id"), table_name="job_skills")
    op.drop_index(op.f("ix_job_skills_job_id"), table_name="job_skills")
    op.drop_table("job_skills")

    op.drop_index("ix_skills_tags", table_name="skills")
    op.drop_index("ix_skills_search_vector", table_name="skills")
    op.drop_index(op.f("ix_skills_is_enabled"), table_name="skills")
    op.drop_index(op.f("ix_skills_source_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.drop_index(op.f("ix_skills_category"), table_name="skills")
    op.drop_table("skills")

    op.drop_index(op.f("ix_skill_sources_source_type"), table_name="skill_sources")
    op.drop_table("skill_sources")
