"""Add job_skills junction table.

Revision ID: add_job_skills_table
Revises: init_full_schema
Create Date: 2026-02-15 10:00:00.000000+00:00

This migration adds the job_skills table for tracking which skills
were used for each job, including snapshot data to preserve skill
content even if the original skill is deleted.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_job_skills_table"
down_revision: Union[str, None] = "init_full_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the job_skills junction table."""
    op.create_table(
        "job_skills",
        sa.Column(
            "job_id",
            sa.UUID(),
            nullable=False,
            comment="Job that uses this skill",
        ),
        sa.Column(
            "skill_id",
            sa.UUID(),
            nullable=True,
            comment="Original skill (NULL if skill was deleted)",
        ),
        sa.Column(
            "skill_name",
            sa.String(length=255),
            nullable=False,
            comment="Skill name at time of selection",
        ),
        sa.Column(
            "skill_category",
            sa.String(length=100),
            nullable=False,
            comment="Skill category at time of selection",
        ),
        sa.Column(
            "skill_content",
            sa.Text(),
            nullable=False,
            comment="Full skill content at time of selection",
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            server_default="initial",
            nullable=False,
            comment="How skill was added: 'initial' (job start) or 'agent' (via MCP tool)",
        ),
        sa.Column(
            "similarity_score",
            sa.Float(),
            nullable=True,
            comment="Relevance score from full-text search (0.0-1.0)",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_skills_job_id"),
        "job_skills",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_skills_skill_id"),
        "job_skills",
        ["skill_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the job_skills table."""
    op.drop_index(op.f("ix_job_skills_skill_id"), table_name="job_skills")
    op.drop_index(op.f("ix_job_skills_job_id"), table_name="job_skills")
    op.drop_table("job_skills")
