"""
Bundle generator for SHANDY research packages.

Creates tgz archives with RO-Crate metadata for complete research packages.
"""

import io
import json
import tarfile
from datetime import datetime
from pathlib import Path


def generate_ro_crate_metadata(job_dir: Path) -> dict:
    """
    Generate RO-Crate 1.1 metadata for a job directory.

    Args:
        job_dir: Path to the job directory

    Returns:
        RO-Crate metadata as a dictionary
    """
    job_id = job_dir.name

    # Load job config for metadata
    config_path = job_dir / "config.json"
    config = {}
    if config_path.exists():
        config = json.loads(config_path.read_text())

    date_created = config.get("created_at", datetime.now().isoformat())

    graph = [
        {
            "@id": "ro-crate-metadata.json",
            "@type": "CreativeWork",
            "about": {"@id": "./"},
            "conformsTo": {"@id": "https://w3id.org/ro/crate/1.1"}
        },
        {
            "@id": "./",
            "@type": "Dataset",
            "name": f"SHANDY Discovery Report - {job_id}",
            "description": "Autonomous scientific discovery results generated by SHANDY",
            "dateCreated": date_created,
            "creator": {"@id": "https://github.com/monarch-initiative/shandy"}
        }
    ]

    # Add report files
    if (job_dir / "final_report.pdf").exists():
        graph.append({
            "@id": "final_report.pdf",
            "@type": "File",
            "name": "Discovery Report (PDF)",
            "encodingFormat": "application/pdf"
        })

    if (job_dir / "final_report.md").exists():
        graph.append({
            "@id": "final_report.md",
            "@type": "File",
            "name": "Discovery Report (Markdown)",
            "encodingFormat": "text/markdown"
        })

    # Add config
    if config_path.exists():
        graph.append({
            "@id": "config.json",
            "@type": "File",
            "name": "Job Configuration",
            "encodingFormat": "application/json"
        })

    # Add knowledge graph
    if (job_dir / "knowledge_graph.json").exists():
        graph.append({
            "@id": "knowledge_graph.json",
            "@type": "File",
            "name": "Knowledge Graph",
            "description": "Structured findings and hypotheses from the discovery process",
            "encodingFormat": "application/json"
        })

    # Add data files
    data_dir = job_dir / "data"
    if data_dir.exists():
        for data_file in data_dir.iterdir():
            if data_file.is_file():
                encoding = "text/csv" if data_file.suffix == ".csv" else "application/octet-stream"
                graph.append({
                    "@id": f"data/{data_file.name}",
                    "@type": "File",
                    "name": f"Input Data: {data_file.name}",
                    "encodingFormat": encoding
                })

    # Add plots
    plots_dir = job_dir / "plots"
    if plots_dir.exists():
        for plot_file in sorted(plots_dir.iterdir()):
            if plot_file.suffix == ".png":
                # Try to get description from companion JSON
                description = None
                meta_file = plot_file.with_suffix(".json")
                if meta_file.exists():
                    meta = json.loads(meta_file.read_text())
                    description = meta.get("description")

                entry = {
                    "@id": f"plots/{plot_file.name}",
                    "@type": ["File", "ImageObject"],
                    "name": plot_file.stem.replace("_", " ").title(),
                    "encodingFormat": "image/png"
                }
                if description:
                    entry["description"] = description
                graph.append(entry)

            elif plot_file.suffix == ".json":
                graph.append({
                    "@id": f"plots/{plot_file.name}",
                    "@type": "File",
                    "name": f"Plot Metadata: {plot_file.stem}",
                    "encodingFormat": "application/json"
                })

    return {
        "@context": "https://w3id.org/ro/crate/1.1/context",
        "@graph": graph
    }


def create_bundle(job_dir: Path) -> bytes:
    """
    Create a tgz bundle of a job directory with RO-Crate metadata.

    Args:
        job_dir: Path to the job directory

    Returns:
        Bytes of the tgz archive
    """
    job_id = job_dir.name
    bundle_name = f"{job_id}_bundle"

    # Create in-memory tar.gz
    buffer = io.BytesIO()

    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        # Generate and add RO-Crate metadata
        ro_crate = generate_ro_crate_metadata(job_dir)
        ro_crate_bytes = json.dumps(ro_crate, indent=2).encode("utf-8")
        ro_crate_info = tarfile.TarInfo(name=f"{bundle_name}/ro-crate-metadata.json")
        ro_crate_info.size = len(ro_crate_bytes)
        ro_crate_info.mtime = int(datetime.now().timestamp())
        tar.addfile(ro_crate_info, io.BytesIO(ro_crate_bytes))

        # Add report files
        for filename in ["final_report.pdf", "final_report.md", "config.json", "knowledge_graph.json"]:
            filepath = job_dir / filename
            if filepath.exists():
                tar.add(filepath, arcname=f"{bundle_name}/{filename}")

        # Add data directory
        data_dir = job_dir / "data"
        if data_dir.exists():
            for data_file in data_dir.iterdir():
                if data_file.is_file():
                    tar.add(data_file, arcname=f"{bundle_name}/data/{data_file.name}")

        # Add plots directory
        plots_dir = job_dir / "plots"
        if plots_dir.exists():
            for plot_file in plots_dir.iterdir():
                if plot_file.is_file():
                    tar.add(plot_file, arcname=f"{bundle_name}/plots/{plot_file.name}")

    buffer.seek(0)
    return buffer.read()
