"""Add MARDUK rare-disease mode: jobs.marduk_enabled + marduk_memories table.

Revision ID: add_marduk
Revises: rename_title_to_rq
Create Date: 2026-07-08 12:00:00.000000+00:00

Adds the per-job ``marduk_enabled`` flag and the ``marduk_memories`` table that
backs MARDUK's persistent, user-scoped cross-job memory. The memory table is
scoped to its owner (not to a job), so ``source_job_id`` uses ON DELETE SET NULL
to keep memories when their originating job is deleted. RLS mirrors the
user-owned pattern used by ``api_keys``: owners get full access, admins get
read-only.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "add_marduk"
down_revision: str = "rename_title_to_rq"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add marduk_enabled column and create marduk_memories with RLS."""
    op.add_column(
        "jobs",
        sa.Column(
            "marduk_enabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether MARDUK rare-disease mode (Monarch tools + memory) is enabled",
        ),
    )

    op.create_table(
        "marduk_memories",
        sa.Column(
            "owner_id",
            sa.UUID(),
            nullable=False,
            comment="User who owns this memory",
        ),
        sa.Column(
            "source_job_id",
            sa.UUID(),
            nullable=True,
            comment="Job that produced this memory (NULL if that job was deleted)",
        ),
        sa.Column(
            "kind",
            sa.String(length=50),
            server_default="insight",
            nullable=False,
            comment="Memory type (insight/mapping/ruled_out/association)",
        ),
        sa.Column(
            "entity_id",
            sa.String(length=255),
            nullable=True,
            comment="Primary Monarch CURIE the memory is about (e.g. MONDO:0007947)",
        ),
        sa.Column(
            "entity_label",
            sa.String(length=500),
            nullable=True,
            comment="Human-readable label for entity_id",
        ),
        sa.Column(
            "title",
            sa.String(length=500),
            nullable=False,
            comment="Short headline for the memory",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="The insight itself",
        ),
        sa.Column(
            "evidence",
            sa.Text(),
            nullable=True,
            comment="Supporting evidence / provenance for the insight",
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
            comment="Free-text tags (diseases, genes, phenotypes) for recall",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether the memory is eligible for recall/injection",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marduk_memories_owner_id"), "marduk_memories", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_marduk_memories_source_job_id"),
        "marduk_memories",
        ["source_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marduk_memories_entity_id"), "marduk_memories", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_marduk_memories_is_active"), "marduk_memories", ["is_active"], unique=False
    )

    # RLS: owner has full access; admins read-only (mirrors api_keys).
    op.execute("ALTER TABLE marduk_memories ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE marduk_memories FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY marduk_memories_all_own ON marduk_memories FOR ALL
            USING (
                current_setting('app.current_user_id', TRUE) IS NOT NULL
                AND owner_id::text = current_setting('app.current_user_id', TRUE)
            )
    """
    )
    op.execute(
        """
        CREATE POLICY marduk_memories_select_admin ON marduk_memories FOR SELECT
            USING (current_user_is_admin())
    """
    )

    op.execute("GRANT ALL ON marduk_memories TO openscientist_app")
    op.execute("GRANT ALL ON marduk_memories TO openscientist_admin")


def downgrade() -> None:
    """Drop marduk_memories and the marduk_enabled column."""
    op.execute("DROP POLICY IF EXISTS marduk_memories_select_admin ON marduk_memories")
    op.execute("DROP POLICY IF EXISTS marduk_memories_all_own ON marduk_memories")
    op.drop_index(op.f("ix_marduk_memories_is_active"), table_name="marduk_memories")
    op.drop_index(op.f("ix_marduk_memories_entity_id"), table_name="marduk_memories")
    op.drop_index(op.f("ix_marduk_memories_source_job_id"), table_name="marduk_memories")
    op.drop_index(op.f("ix_marduk_memories_owner_id"), table_name="marduk_memories")
    op.drop_table("marduk_memories")
    op.drop_column("jobs", "marduk_enabled")
